apiVersion: admitik.freepik.com/v1alpha1
kind: ClusterGenerationPolicy
metadata:
  name: cel-generate-configmap
spec:
  #overwriteExisting: true

  # Resources to be watched
  watchedResources:
    group: ""
    version: v1
    resource: namespaces
    #name: ""
    #namespace: ""

  # Other resources to be retrieved for conditions templates.
  # They will be included under .sources scope in the template
  sources: []

  conditions:
    - name: second-condition
      engine: cel
      key: |
        object.metadata.name
      value: "pass"

  object:
    clone: {}
    definition:
      engine: cel
      template: |
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: whatever-config
          namespace: "{{ object.metadata.name }}"
        data:
          KEY_1: "whatever"
          KEY_2: "whatismore"
