apiVersion: admitik.freepik.com/v1alpha1
kind: ClusterValidationPolicy
metadata:
  name: gotmpl-avoid-colliding-routes
spec:
  failureAction: Permissive

  # Resources to be intercepted before reaching the cluster
  interceptedResources:
    group: gateway.networking.k8s.io
    version: v1
    resource: httproutes
    operations:
      - CREATE
      - UPDATE

  # Other resources to be retrieved for conditions templates.
  # They will be included under .sources scope in the template
  sources:
    - group: gateway.networking.k8s.io
      version: v1
      resource: httproutes

      # (Optional) It's possible to retrieve specific resources
      # name: secondary-route
      # namespace: default

  conditions:
    - name: confirm-non-existing-routes

      # The 'engine' field decides between:
      # * gotmpl:   (default) Vitamin Golang templating (well known from Helm)
      # * starlark: Starlark from Google
      engine: gotmpl

      # The 'key' field is the place to write your template or code
      # The result of this field will be compared with 'value' for equality
      key: |
        {{- $object := .object -}}
        {{- $sources := .sources -}}
        {{- $routeFound := false -}}

        {{- $routes := (index .sources 0) -}}
        {{- range $routeObjIndex, $routeObj := $routes -}}

          {{/* Here some logic to confirm you found the route already existing */}}
          {{- $routeFound := true -}}

        {{- end -}}

        {{- if $routeFound -}}
          {{- printf "route-already-created" -}}
        {{- else -}}
          {{- printf "route-not-found" -}}
        {{- end -}}

      value: "route-not-found"

  message:
    template: |
      {{- $object := .object -}}
      {{- printf "Resource '%s' was rejected as some of declared routes already exists" $object.metadata.name -}}
