apiVersion: admitik.freepik.com/v1alpha1
kind: ClusterMutationPolicy
metadata:
  name: test
spec:

  failureAction: Permissive

  # Resources to be watched
  watchedResources:
    group: ""
    version: v1
    resource: namespaces
    operations:
      - CREATE
      - UPDATE

  # Other resources to be retrieved for conditions templates.
  # They will be included under .sources scope in the template
  sources: []

  conditions:
    - name: first-condition
      engine: starlark
      key: |
        print("pass")
      value: "pass"

    - name: second-condition
      engine: starlark
      key: |
        print("pass")
      value: "pass"

  patch:
    type: JsonPatch # JsonPatch | StrategicMerge | ServerSideApply
    engine: starlark # plain | gotmpl | starlark
    template: |
      if object.get("metadata", {}).get("labels", {}).get("apply-patch") == "true":
      
        patch = [
            {"op": "add", "path": "/spec/newField", "value": "newValue"},
            {"op": "replace", "path": "/metadata/annotations/updated", "value": "yes"},
            {"op": "remove", "path": "/status/oldField"}
        ]
