apiVersion: admitik.freepik.com/v1alpha1
kind: ClusterMutationPolicy
metadata:
  name: starlark-add-some-labels
spec:
  # TODO: Implement failureAction for mutations
  # failureAction: Permissive

  # Resources to be intercepted before reaching the cluster
  interceptedResources:
    group: ""
    version: v1
    resource: namespaces
    operations:
      - CREATE
      - UPDATE

  # Other resources to be retrieved for conditions templates.
  # They will be included under .sources scope in the template
  sources: []

  conditions:
    - name: first-condition
      engine: starlark
      key: |
        print("pass")
      value: "pass"

  patch:
    type: jsonpatch # JsonPatch | StrategicMerge
    engine: starlark
    template: |
      patch = [
          {"op": "add", "path": "/metadata/annotations/first", "value": "firstValue"},
          {"op": "replace", "path": "/metadata/annotations/second", "value": "secondValue"},
      ]
      print(json.encode(patch))
