apiVersion: admitik.freepik.com/v1alpha1
kind: ClusterMutationPolicy
metadata:
  name: plain-with-cel-add-some-labels
spec:

  # Resources to be intercepted before reaching the cluster
  interceptedResources:
    group: ""
    version: v1
    resource: namespaces
    operations:
      - CREATE
      - UPDATE

  # Other resources to be retrieved for conditions templates.
  # They will be included under .sources scope in the template
  sources: []

  # Conditions are optional, so no-conditions means they are always met
  conditions: []

  patch:
    type: jsonpatch # JsonPatch | StrategicMerge
    engine: starlark
    template: |
      {[
          {"op": "add", "path": "/metadata/annotations/objectname", "value": "{{cel: object.metadata.name }}"},
          {"op": "replace", "path": "/metadata/annotations/objectnamespace", "value": "{{cel: object.metadata.namespace }}"},
      ]}
