# permissions for end users to view clustermutationpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: admitik
    app.kubernetes.io/managed-by: kustomize
  name: clustermutationpolicy-viewer-role
rules:
- apiGroups:
  - admitik.dev
  resources:
  - clustermutationpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admitik.dev
  resources:
  - clustermutationpolicies/status
  verbs:
  - get
