# permissions for end users to edit clustervalidationpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: admitik
    app.kubernetes.io/managed-by: kustomize
  name: clustervalidationpolicy-editor-role
rules:
- apiGroups:
  - admitik.dev
  resources:
  - clustervalidationpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admitik.dev
  resources:
  - clustervalidationpolicies/status
  verbs:
  - get
