---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admitik.freepik.com
  resources:
  - clusteradmissionpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admitik.freepik.com
  resources:
  - clusteradmissionpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - admitik.freepik.com
  resources:
  - clusteradmissionpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - admitik.freepik.com
  resources:
  - clustermutationpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admitik.freepik.com
  resources:
  - clustermutationpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - admitik.freepik.com
  resources:
  - clustermutationpolicies/status
  verbs:
  - get
  - patch
  - update
