//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	admissionregistrationv1 "k8s.io/api/admissionregistration/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdmissionResourceGroupT) DeepCopyInto(out *AdmissionResourceGroupT) {
	*out = *in
	out.GroupVersionResource = in.GroupVersionResource
	if in.Operations != nil {
		in, out := &in.Operations, &out.Operations
		*out = make([]admissionregistrationv1.OperationType, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdmissionResourceGroupT.
func (in *AdmissionResourceGroupT) DeepCopy() *AdmissionResourceGroupT {
	if in == nil {
		return nil
	}
	out := new(AdmissionResourceGroupT)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGenerationPolicy) DeepCopyInto(out *ClusterGenerationPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGenerationPolicy.
func (in *ClusterGenerationPolicy) DeepCopy() *ClusterGenerationPolicy {
	if in == nil {
		return nil
	}
	out := new(ClusterGenerationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterGenerationPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGenerationPolicyList) DeepCopyInto(out *ClusterGenerationPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterGenerationPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGenerationPolicyList.
func (in *ClusterGenerationPolicyList) DeepCopy() *ClusterGenerationPolicyList {
	if in == nil {
		return nil
	}
	out := new(ClusterGenerationPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterGenerationPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGenerationPolicySpec) DeepCopyInto(out *ClusterGenerationPolicySpec) {
	*out = *in
	out.WatchedResources = in.WatchedResources
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]ResourceGroupT, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ConditionT, len(*in))
		copy(*out, *in)
	}
	out.Object = in.Object
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGenerationPolicySpec.
func (in *ClusterGenerationPolicySpec) DeepCopy() *ClusterGenerationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ClusterGenerationPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGenerationPolicyStatus) DeepCopyInto(out *ClusterGenerationPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGenerationPolicyStatus.
func (in *ClusterGenerationPolicyStatus) DeepCopy() *ClusterGenerationPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterGenerationPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterMutationPolicy) DeepCopyInto(out *ClusterMutationPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterMutationPolicy.
func (in *ClusterMutationPolicy) DeepCopy() *ClusterMutationPolicy {
	if in == nil {
		return nil
	}
	out := new(ClusterMutationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterMutationPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterMutationPolicyList) DeepCopyInto(out *ClusterMutationPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterMutationPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterMutationPolicyList.
func (in *ClusterMutationPolicyList) DeepCopy() *ClusterMutationPolicyList {
	if in == nil {
		return nil
	}
	out := new(ClusterMutationPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterMutationPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterMutationPolicySpec) DeepCopyInto(out *ClusterMutationPolicySpec) {
	*out = *in
	in.WatchedResources.DeepCopyInto(&out.WatchedResources)
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]ResourceGroupT, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ConditionT, len(*in))
		copy(*out, *in)
	}
	out.Patch = in.Patch
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterMutationPolicySpec.
func (in *ClusterMutationPolicySpec) DeepCopy() *ClusterMutationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ClusterMutationPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterMutationPolicyStatus) DeepCopyInto(out *ClusterMutationPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterMutationPolicyStatus.
func (in *ClusterMutationPolicyStatus) DeepCopy() *ClusterMutationPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterMutationPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterValidationPolicy) DeepCopyInto(out *ClusterValidationPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterValidationPolicy.
func (in *ClusterValidationPolicy) DeepCopy() *ClusterValidationPolicy {
	if in == nil {
		return nil
	}
	out := new(ClusterValidationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterValidationPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterValidationPolicyList) DeepCopyInto(out *ClusterValidationPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterValidationPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterValidationPolicyList.
func (in *ClusterValidationPolicyList) DeepCopy() *ClusterValidationPolicyList {
	if in == nil {
		return nil
	}
	out := new(ClusterValidationPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterValidationPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterValidationPolicySpec) DeepCopyInto(out *ClusterValidationPolicySpec) {
	*out = *in
	in.WatchedResources.DeepCopyInto(&out.WatchedResources)
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]ResourceGroupT, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ConditionT, len(*in))
		copy(*out, *in)
	}
	out.Message = in.Message
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterValidationPolicySpec.
func (in *ClusterValidationPolicySpec) DeepCopy() *ClusterValidationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ClusterValidationPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterValidationPolicyStatus) DeepCopyInto(out *ClusterValidationPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterValidationPolicyStatus.
func (in *ClusterValidationPolicyStatus) DeepCopy() *ClusterValidationPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterValidationPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionT) DeepCopyInto(out *ConditionT) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionT.
func (in *ConditionT) DeepCopy() *ConditionT {
	if in == nil {
		return nil
	}
	out := new(ConditionT)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessageT) DeepCopyInto(out *MessageT) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessageT.
func (in *MessageT) DeepCopy() *MessageT {
	if in == nil {
		return nil
	}
	out := new(MessageT)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectCloneT) DeepCopyInto(out *ObjectCloneT) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectCloneT.
func (in *ObjectCloneT) DeepCopy() *ObjectCloneT {
	if in == nil {
		return nil
	}
	out := new(ObjectCloneT)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectDefinitionT) DeepCopyInto(out *ObjectDefinitionT) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectDefinitionT.
func (in *ObjectDefinitionT) DeepCopy() *ObjectDefinitionT {
	if in == nil {
		return nil
	}
	out := new(ObjectDefinitionT)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectT) DeepCopyInto(out *ObjectT) {
	*out = *in
	out.Clone = in.Clone
	out.Definition = in.Definition
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectT.
func (in *ObjectT) DeepCopy() *ObjectT {
	if in == nil {
		return nil
	}
	out := new(ObjectT)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatchT) DeepCopyInto(out *PatchT) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatchT.
func (in *PatchT) DeepCopy() *PatchT {
	if in == nil {
		return nil
	}
	out := new(PatchT)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceGroupT) DeepCopyInto(out *ResourceGroupT) {
	*out = *in
	out.GroupVersionResource = in.GroupVersionResource
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceGroupT.
func (in *ResourceGroupT) DeepCopy() *ResourceGroupT {
	if in == nil {
		return nil
	}
	out := new(ResourceGroupT)
	in.DeepCopyInto(out)
	return out
}
