apiVersion: admitik.freepik.com/v1alpha1
kind: ClusterGenerationPolicy
metadata:
  name: plain-with-cel-generate-configmap
spec:

  overwriteExisting: true

  # Resources to be watched
  watchedResources:
    - group: ""
      version: v1
      resource: namespaces
      #name: ""
      #namespace: ""

  # Other resources to be retrieved for conditions templates.
  # They will be included under .sources scope in the template
  sources:
    - group: ""
      version: v1
      resource: configmaps

  conditions:
    - name: first-condition
      engine: cel
      key: |
        object.metadata.name
      value: "default"

  object:
    clone: {}
    definition:
      engine: plain+cel
      template: |
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: whatever-config
          namespace: "{{cel: object.metadata.name }}"
        data:
          FIRST_SOURCE_ITEM_NAME: "{{cel: sources[0][0].metadata.name }}"
          FIRST_SOURCE_ITEM_NAMESPACE: "{{cel: sources[0][0].metadata.namespace }}"
