apiVersion: admitik.dev/v1alpha1
kind: ClusterMutationPolicy
metadata:
  name: 01-plain-with-cel-use-jsonmerge-patch
spec:

  # Priority represents the order in which the policies will be evaluated.
  # Higher numbers will be evaluated later.
  # priority: 1001

  # Resources to be intercepted before reaching the cluster
  interceptedResources:
    - group: ""
      version: v1
      resource: namespaces
      operations:
        - CREATE

  # Other resources to be retrieved for conditions templates.
  # They will be included under .sources scope in the template
  sources: []

  # Conditions are optional, so no-conditions means they are always met
  conditions: []

  patch:
    type: jsonmerge # JsonPatch | JsonMerge | StrategicMerge
    engine: plain+cel
    template: |
      metadata:
        labels:
          patch-01-custom-label/namespace: "{{cel: object.metadata.name }}"
