apiVersion: admitik.dev/v1alpha1
kind: ClusterMutationPolicy
metadata:
  name: 05-plain-with-cel-add-some-labels-with-sources
spec:

  # Priority represents the order in which the policies will be evaluated.
  # Higher numbers will be evaluated later.
  # priority: 1005

  # Resources to be intercepted before reaching the cluster
  interceptedResources:
    - group: ""
      version: v1
      resource: namespaces
      operations:
        - CREATE

  # Other resources to be retrieved for conditions templates.
  # They will be included under .sources scope in the template
  sources:
    - group: ""
      version: v1
      resource: configmaps
      filters:
        namespace:
          matchList:
            - kube-system
            - "{{cel: object.metadata.name }}"

  conditions:
    - name: ensure-labels-exist
      engine: cel
      key: has(object.metadata.labels)
      value: "true"

  patch:
    type: jsonpatch # JsonPatch | JsonMerge | StrategicMerge
    engine: plain+cel
    template: |
      [
        { "op": "add", "path": "/metadata/labels/patch-05-configmaps-count", "value": "{{cel: sources[0].size() }}" }
      ]
