apiVersion: admitik.dev/v1alpha1
kind: ClusterMutationPolicy
metadata:
  name: plain-with-cel-add-some-labels
spec:

  # Resources to be intercepted before reaching the cluster
  interceptedResources:
    - group: ""
      version: v1
      resource: namespaces
      operations:
        - CREATE

  # Other resources to be retrieved for conditions templates.
  # They will be included under .sources scope in the template
  sources: []

  # Conditions are optional, so no-conditions means they are always met
  conditions: []

  patch:
    type: jsonpatch # JsonPatch | JsonMerge | StrategicMerge
    engine: plain+cel
    template: |
      [
        { "op": "add", "path": "/metadata/annotations", "value": {} },
        { "op": "add", "path": "/metadata/annotations/object-operation", "value": "{{cel: operation }}" },
        { "op": "add", "path": "/metadata/annotations/object-kind", "value": "{{cel: object.kind }}" },
        { "op": "add", "path": "/metadata/annotations/object-name", "value": "{{cel: object.metadata.name }}" }
      ]
