apiVersion: admitik.dev/v1alpha1
kind: ClusterClonePolicy
metadata:
  name: 01-clone-configmap-to-namespaces
spec:

  overwriteExisting: true

  # Watch for ConfigMap changes in the "shared" namespace
  watchedResources:
    - group: ""
      version: v1
      resource: configmaps
      name: shared-config
      namespace: shared

  # Clone whenever the watched ConfigMap is created or updated
  conditions:
    - name: on-change
      engine: cel
      key: |
        operation == "CREATE" || operation == "UPDATE"
      value: "true"

  # Clone to these specific namespaces
  target:
    - namespace:
        names:
          - team-a
          - team-b
          - team-c
