apiVersion: admitik.dev/v1alpha1
kind: ClusterClonePolicy
metadata:
  name: 02-clone-secret-with-label-selector
spec:

  overwriteExisting: true

  # Watch for secrets in the "infra" namespace
  watchedResources:
    - group: ""
      version: v1
      resource: secrets
      name: ""
      namespace: infra

  # Only clone secrets that carry the "clone-me: true" label
  conditions:
    - name: has-clone-label
      engine: cel
      key: |
        has(object.metadata.labels) && "clone-me" in object.metadata.labels && object.metadata.labels["clone-me"] == "true"
      value: "true"

  # Clone to all namespaces with the "env: production" label
  target:
    - namespace:
        labelSelector:
          matchLabels:
            env: production
