labels:
  - pairs:
      app.kubernetes.io/name: admitik
      app.kubernetes.io/managed-by: kustomize

resources:

#####################################
## ClusterValidationPolicy
#####################################

# CEL examples

# Gotmpl examples
- ClusterValidationPolicies/gotmpl_existing_labels.yaml
- ClusterValidationPolicies/gotmpl_avoid_colliding_routes.yaml

# Starlark examples
- ClusterValidationPolicies/starlark_existing_labels.yaml
- ClusterValidationPolicies/starlark_avoid_colliding_routes.yaml
- ClusterValidationPolicies/starlark_populate_vars.yaml

# Plain examples

# Plain+CEL examples

#####################################
## ClusterMutationPolicy
#####################################

# CEL examples

# Gotmpl examples

# Starlark examples
- ClusterMutationPolicy/starlark_add_some_labels.yaml

# Plain examples

# Plain+CEL examples
- ClusterMutationPolicy/plain_with_cel_add_some_labels.yaml

#####################################
## ClusterGenerationPolicy
#####################################

# CEL examples

# Gotmpl examples

# Starlark examples

# Plain examples
- ClusterGenerationPolicy/plain_generate_configmap.yaml

# Plain+CEL examples
- ClusterGenerationPolicy/plain_with_cel_generate_configmap.yaml
